### ISSUE TITLE
'OpenAIEmbeddings' object has no attribute 'request_timeout

### ISSUE THREAD

**Issue by SwarnaLatchumi** [hwchase17/langchain-hub#41]
Can someone help on this issue please ? 

1683790196853	ERROR	AttributeError("'OpenAIEmbeddings' object has no attribute 'request_timeout'")
Traceback (most recent call last):
  File "/Users/swarna-10535/Library/Application Support/zcatalyst-cli-runtimes/python/zcatalyst_runtime_39/main.py", line 72, in customer_request_handler
    FLAVOUR_HANDLER.invoke_handler()
  File "/Users/swarna-10535/Library/Application Support/zcatalyst-cli-runtimes/python/zcatalyst_runtime_39/flavours/__init__.py", line 53, in invoke_handler
    RET = CUSTOMER_CODE_ENTRYPOINT(*(self.__construct_function_parameters()))
  File "/Users/swarna-10535/catalyst_work_dir/.build/functions/zoho_inventory_ai_function/main.py", line 516, in handler
    docs = docsearch.similarity_search(req_data.get("question"))
  File "/Users/swarna-10535/catalyst_work_dir/.build/functions/zoho_inventory_ai_function/langchain/vectorstores/faiss.py", line 226, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k)
  File "/Users/swarna-10535/catalyst_work_dir/.build/functions/zoho_inventory_ai_function/langchain/vectorstores/faiss.py", line 195, in similarity_search_with_score
    embedding = self.embedding_function(query)
  File "/Users/swarna-10535/catalyst_work_dir/.build/functions/zoho_inventory_ai_function/langchain/embeddings/openai.py", line 286, in embed_query
    embedding = self._embedding_func(text, engine=self.deployment)
  File "/Users/swarna-10535/catalyst_work_dir/.build/functions/zoho_inventory_ai_function/langchain/embeddings/openai.py", line 257, in _embedding_func
    self, input=[text], engine=engine, request_timeout=self.request_timeout
AttributeError: 'OpenAIEmbeddings' object has no attribute 'request_timeout'

**Comment by weitang2022** [comment]
Facing the same error... To get around, changed the source code `request_timeout=120` and it worked

**Comment by tejasparekh83** [comment]
I am also facing same issue.

**Comment by yinfeifan** [comment]
how can we solve this problem?

**Comment by tabee** [comment]
same with 0.0.169:

Traceback (most recent call last):
  File "C:\Users\beema\Code\LangChainSchoolPro\QA_bot\qa_chains.py", line 130, in <module>
    docs = mmr_retriever.get_relevant_documents(query)
  File "C:\Users\beema\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\base.py", line 375, in get_relevant_documents
    docs = self.vectorstore.max_marginal_relevance_search(
  File "C:\Users\beema\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\faiss.py", line 299, in max_marginal_relevance_search
    embedding = self.embedding_function(query)
  File "C:\Users\beema\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\embeddings\openai.py", line 293, in embed_query
    embedding = self._embedding_func(text, engine=self.deployment)
  File "C:\Users\beema\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\embeddings\openai.py", line 263, in _embedding_func
    request_timeout=self.request_timeout,
AttributeError: 'OpenAIEmbeddings' object has no attribute 'request_timeout'
PS C:\Users\beema\Code\LangChainSchoolPro\QA_bot> 


with 0.0.155 was everything fine.

**Comment by mbiss10** [comment]
I was getting this error because I was trying to query from a vectorstore that I'd created using an earlier langchain version. I pickled the vectorstore object and unpickled it when I needed to retrieve documents from it. I think the problem is that the OpenAI embeddings I used to create the vectorstore are outdated now and don't support the same interface as OpenAI embeddings in more recent langchain versions, so I just had to recreate the vectorstore using the exact same code as I originally used. Re-running this allowed the stored embeddings to match the new langchain code and solved my problem. Hope that helps.

**Comment by NHNguyen94** [comment]
> I was getting this error because I was trying to query from a vectorstore that I'd created using an earlier langchain version. I pickled the vectorstore object and unpickled it when I needed to retrieve documents from it. I think the problem is that the OpenAI embeddings I used to create the vectorstore are outdated now and don't support the same interface as OpenAI embeddings in more recent langchain versions, so I just had to recreate the vectorstore using the exact same code as I originally used. Re-running this allowed the stored embeddings to match the new langchain code and solved my problem. Hope that helps.

You have saved my day! I have spent 2 days trying to fix this bug, until I read your post...
Thank you!

**Comment by aiakubovich** [comment]
> I was getting this error because I was trying to query from a vectorstore that I'd created using an earlier langchain version. I pickled the vectorstore object and unpickled it when I needed to retrieve documents from it. I think the problem is that the OpenAI embeddings I used to create the vectorstore are outdated now and don't support the same interface as OpenAI embeddings in more recent langchain versions, so I just had to recreate the vectorstore using the exact same code as I originally used. Re-running this allowed the stored embeddings to match the new langchain code and solved my problem. Hope that helps.

THANK YOU!!! I was trying to solve it for hours but solution was to remove previous pkl files from Faiss

**Comment by wmgillett** [comment]
I am doing the same thing - reusing pkl files and ran into this same issue when upgrading langchain.  This fix worked great to rebuild pkl files.  I guess for now, I need to avoid reusing pkl files and rebuild the pkl files each time.
