### ISSUE TITLE
AttributeError: 'FAISS' object has no attribute '_normalize_L2'

### ISSUE THREAD

**Issue by SwarnaLatchumi** [hwchase17/langchain-hub#42]
Traceback (most recent call last):
  File "/Users/swarna-10535/Library/Application Support/zcatalyst-cli-runtimes/python/zcatalyst_runtime_39/main.py", line 72, in customer_request_handler
    FLAVOUR_HANDLER.invoke_handler()
  File "/Users/swarna-10535/Library/Application Support/zcatalyst-cli-runtimes/python/zcatalyst_runtime_39/flavours/__init__.py", line 53, in invoke_handler
    RET = CUSTOMER_CODE_ENTRYPOINT(*(self.__construct_function_parameters()))
  File "/Users/swarna-10535/Working_Test_books/.build/functions/zoho_inventory_ai_function/main.py", line 1412, in handler
    docs = docsearch.similarity_search(req_data.get("question")+"\nLink:",k=3)
  File "/Users/swarna-10535/Working_Test_books/.build/functions/zoho_inventory_ai_function/langchain/vectorstores/faiss.py", line 251, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k)
  File "/Users/swarna-10535/Working_Test_books/.build/functions/zoho_inventory_ai_function/langchain/vectorstores/faiss.py", line 221, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(embedding, k)
  File "/Users/swarna-10535/Working_Test_books/.build/functions/zoho_inventory_ai_function/langchain/vectorstores/faiss.py", line 193, in similarity_search_with_score_by_vector
    if self._normalize_L2:
AttributeError: 'FAISS' object has no attribute '_normalize_L2'

**Comment by oqp** [comment]
I got that error when I developed in Windows everything was working but at the moment to publish in Linux I copied the vectorStore's file. I deleted that file and I generated it again directly in linux and everything worked again. I hope it could help you too.

**Comment by SwarnaLatchumi** [comment]
> developed

Thank you. Will retry again.

**Comment by jpzhangvincent** [comment]
ya same issue. why is it the case? Is there a way to convert the format or make sure the faiss object working in both envs?
